### ISSUE TITLE
go get github.com/martin-helmich/kubernetes-crd-example gives error

### ISSUE THREAD

**Issue by onkarbanerjee** [martin-helmich/kubernetes-crd-example#1]
go get github.com/martin-helmich/kubernetes-crd-example
github.com/martin-helmich/kubernetes-crd-example/clientset/v1alpha1
go\src\github.com\martin-helmich\kubernetes-crd-example\clientset\v1alpha1\api.go:6:2: imported and not used: "k8s.io/apimachinery/pkg/runtime/serializer"
go\src\github.com\martin-helmich\kubernetes-crd-example\clientset\v1alpha1\projects.go:31:5: not enough arguments in call to c.restClient.Get().Namespace(c.ns).Resource("projects").VersionedParams(&opts, scheme.ParameterCodec).Do
        have ()
        want (context.Context)
go\src\github.com\martin-helmich\kubernetes-crd-example\clientset\v1alpha1\projects.go:45:5: not enough arguments in call to c.restClient.Get().Namespace(c.ns).Resource("projects").Name(name).VersionedParams(&opts, scheme.ParameterCodec).Do
        have ()
        want (context.Context)
go\src\github.com\martin-helmich\kubernetes-crd-example\clientset\v1alpha1\projects.go:58:5: not enough arguments in call to c.restClient.Post().Namespace(c.ns).Resource("projects").Body(project).Do
        have ()
        want (context.Context)
go\src\github.com\martin-helmich\kubernetes-crd-example\clientset\v1alpha1\projects.go:71:8: not enough arguments in call to c.restClient.Get().Namespace(c.ns).Resource("projects").VersionedParams(&opts, scheme.ParameterCodec).Watch
        have ()
        want (context.Context)

**Comment by ruckc** [comment]
@onkarbanerjee - how did you resolve this?
